const image = (query) =>
  `https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80`;
const destinations = [
  ["ahmedabad", "Ahmedabad", "India", 2, 78],
  ["surat", "Surat", "India", 2, 70],
  ["vadodara", "Vadodara", "India", 2, 68],
  ["kutch", "Kutch", "India", 2, 76],
  ["dwarka", "Dwarka", "India", 2, 74],
  ["somnath", "Somnath", "India", 2, 73],
  ["statue-of-unity", "Statue of Unity", "India", 2, 80],
  ["gir", "Gir", "India", 2, 72],
  ["saputara", "Saputara", "India", 2, 69],
  ["jaipur", "Jaipur", "India", 2, 92],
  ["udaipur", "Udaipur", "India", 3, 89],
  ["jodhpur", "Jodhpur", "India", 2, 84],
  ["jaisalmer", "Jaisalmer", "India", 2, 82],
  ["pushkar", "Pushkar", "India", 2, 78],
  ["mount-abu", "Mount Abu", "India", 2, 70],
  ["bikaner", "Bikaner", "India", 2, 68],
  ["ranthambore", "Ranthambore", "India", 3, 79],
  ["mumbai", "Mumbai", "India", 4, 95],
  ["pune", "Pune", "India", 2, 80],
  ["lonavala", "Lonavala", "India", 2, 78],
  ["mahabaleshwar", "Mahabaleshwar", "India", 2, 76],
  ["nashik", "Nashik", "India", 2, 74],
  ["aurangabad", "Aurangabad", "India", 2, 77],
  ["alibaug", "Alibaug", "India", 3, 73],
  ["panaji", "Panaji", "India", 3, 86],
  ["north-goa", "North Goa", "India", 3, 88],
  ["south-goa", "South Goa", "India", 3, 81],
  ["kochi", "Kochi", "India", 2, 84],
  ["munnar", "Munnar", "India", 2, 86],
  ["alappuzha", "Alappuzha", "India", 2, 79],
  ["varkala", "Varkala", "India", 2, 78],
  ["thekkady", "Thekkady", "India", 2, 75],
  ["kovalam", "Kovalam", "India", 2, 76],
  ["shimla", "Shimla", "India", 3, 84],
  ["manali", "Manali", "India", 3, 89],
  ["dharamshala", "Dharamshala", "India", 2, 80],
  ["kasol", "Kasol", "India", 2, 76],
  ["spiti-valley", "Spiti Valley", "India", 3, 74],
  ["rishikesh", "Rishikesh", "India", 2, 87],
  ["mussoorie", "Mussoorie", "India", 2, 80],
  ["nainital", "Nainital", "India", 2, 78],
  ["auli", "Auli", "India", 3, 72],
  ["jim-corbett", "Jim Corbett", "India", 3, 77],
  ["srinagar", "Srinagar", "India", 3, 88],
  ["gulmarg", "Gulmarg", "India", 4, 83],
  ["pahalgam", "Pahalgam", "India", 3, 81],
  ["sonamarg", "Sonamarg", "India", 3, 76],
  ["bengaluru", "Bengaluru", "India", 3, 90],
  ["mysuru", "Mysuru", "India", 2, 82],
  ["coorg", "Coorg", "India", 2, 79],
  ["hampi", "Hampi", "India", 2, 83],
  ["gokarna", "Gokarna", "India", 2, 78],
  ["chennai", "Chennai", "India", 3, 85],
  ["ooty", "Ooty", "India", 2, 81],
  ["kodaikanal", "Kodaikanal", "India", 2, 78],
  ["madurai", "Madurai", "India", 2, 82],
  ["rameswaram", "Rameswaram", "India", 2, 74],
  ["kolkata", "Kolkata", "India", 2, 86],
  ["darjeeling", "Darjeeling", "India", 2, 84],
  ["kalimpong", "Kalimpong", "India", 2, 70],
  ["gangtok", "Gangtok", "India", 2, 78],
  ["shillong", "Shillong", "India", 2, 75],
  ["tawang", "Tawang", "India", 3, 68],
  ["kaziranga", "Kaziranga", "India", 3, 73],
  ["new-delhi", "New Delhi", "India", 3, 94],
  ["agra", "Agra", "India", 2, 93],
  ["varanasi", "Varanasi", "India", 2, 91],
  ["amritsar", "Amritsar", "India", 2, 85],
  ["hyderabad", "Hyderabad", "India", 2, 86],
  ["kyoto", "Kyoto", "Japan", 4, 94],
  ["osaka", "Osaka", "Japan", 4, 91],
  ["nara", "Nara", "Japan", 3, 82],
  ["seoul", "Seoul", "South Korea", 4, 93],
  ["busan", "Busan", "South Korea", 3, 84],
  ["bangkok", "Bangkok", "Thailand", 2, 92],
  ["phuket", "Phuket", "Thailand", 3, 88],
  ["krabi", "Krabi", "Thailand", 2, 82],
  ["chiang-mai", "Chiang Mai", "Thailand", 2, 81],
  ["jakarta", "Jakarta", "Indonesia", 2, 83],
  ["yogyakarta", "Yogyakarta", "Indonesia", 2, 79],
  ["abu-dhabi", "Abu Dhabi", "UAE", 4, 83],
  ["los-angeles", "Los Angeles", "USA", 5, 89],
  ["san-francisco", "San Francisco", "USA", 5, 91],
  ["las-vegas", "Las Vegas", "USA", 5, 86],
  ["miami", "Miami", "USA", 4, 85],
  ["sydney", "Sydney", "Australia", 5, 91],
  ["melbourne", "Melbourne", "Australia", 4, 87],
  ["gold-coast", "Gold Coast", "Australia", 4, 80],
  ["istanbul", "Istanbul", "Turkey", 3, 91],
  ["cappadocia", "Cappadocia", "Turkey", 3, 87],
  ["cairo", "Cairo", "Egypt", 2, 86],
  ["luxor", "Luxor", "Egypt", 2, 80],
  ["amsterdam", "Amsterdam", "Netherlands", 4, 89],
  ["prague", "Prague", "Czech Republic", 3, 86],
  ["vienna", "Vienna", "Austria", 4, 85],
  ["swiss-alps", "Swiss Alps", "Switzerland", 5, 88],
];
const activity = (city, name, category, cost, duration) => ({
  id: `${city}-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
  city_id: city,
  name,
  category,
  cost,
  duration_minutes: duration,
  image_url: image(name),
  description: `A memorable ${category} experience that reveals the character of this destination.`,
});
const templates = [
  ["Highlights & heritage", "sightseeing", 35, 180],
  ["Local flavours walk", "food", 45, 150],
  ["Art and culture visit", "culture", 30, 120],
  ["Outdoor escape", "nature", 40, 180],
  ["Sunset discovery", "adventure", 38, 150],
];
export const CATALOG_CITIES = destinations.map(
  ([id, name, country, cost_index, popularity]) => ({
    id,
    name,
    country,
    cost_index,
    popularity,
    image_url: image(name),
  }),
);
export const CATALOG_ACTIVITIES = CATALOG_CITIES.flatMap((c) =>
  templates.map(([suffix, cat, cost, duration]) =>
    activity(c.id, `${c.name} ${suffix}`, cat, cost, duration),
  ),
);
